### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by AriHenrique** [lovebailin/Andromeda-84#2]
![image](https://github.com/user-attachments/assets/81be33da-ac1f-4333-a2d6-f84156cb7a42)

Hi, I have a problem where the plugin can't activate neon or deactivate it either. I once had this problem and I managed to solve it by renaming a folder or file (I don't remember anymore haha). If anyone is also having this problem or has a solution I would be grateful. I'm using Windows and WSL.

Thx

**Comment by LiuBairin** [comment]
![Image](https://github.com/user-attachments/assets/9cc090dc-3023-4927-a721-ac6c79fdd57f) 
You can refer to this image, which essentially adds a new js file to a folder and references it in the html

**Comment by AriHenrique** [comment]
the neondreams.js script does not exist in my folder

![Image](https://github.com/user-attachments/assets/c748ede3-b8f2-4c00-a13c-677b312f288e)

**Comment by AriHenrique** [comment]
![Image](https://github.com/user-attachments/assets/ee225857-2854-4b78-a850-23ab8d214055)

**Comment by LiuBairin** [comment]
I released the latest 1.0.9 to try to fix this, you can update it to try it out

**Comment by RedAkatsuki** [comment]
Hi,

I have the same problem, my VS code is newly installed (ver 1.98.2) and I installed the latest version of the plugin 1.0.9, and the problem persists. I use Windows 11.


Thx

**Comment by LiuBairin** [comment]
The original file path has changed since vscode 1.9.4 and I have fixed it in plugin version 1.1.0

**Comment by AriHenrique** [comment]
It seems to have been resolved, version 1.1.0 worked here on both Windows and Linux. THX @LiuBairin 

![Image](https://github.com/user-attachments/assets/0adc7dff-0567-4a72-ae2c-8e96728f30a6)

![Image](https://github.com/user-attachments/assets/74e1271c-fefc-4b4f-bb20-b0de1f940c2e)
